# Generated by Django 5.2.5 on 2026-08-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("timezone", models.CharField(default="Asia/Shanghai", max_length=64)),
                ("status", models.CharField(default="active", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("current_cursor", models.PositiveBigIntegerField(default=0)),
                ("minimum_cursor", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.BigIntegerField()),
                ("deleted_at", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=30)),
                ("status", models.CharField(default="active", max_length=24)),
                ("created_at", models.BigIntegerField()),
                ("deleted_at", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PantryBatch",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("ingredient_id", models.CharField(max_length=80)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("original_quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit", models.CharField(max_length=16)),
                ("purchased_at", models.CharField(max_length=10)),
                ("storage_mode", models.CharField(max_length=16)),
                ("shelf_life_days_override", models.PositiveIntegerField(null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted_at", models.BigIntegerField(null=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("ingredient_id", models.CharField(max_length=80)),
                ("suggested_quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit", models.CharField(max_length=16)),
                ("source_recipe_id", models.CharField(blank=True, max_length=80)),
                ("checked", models.BooleanField(default=False)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted_at", models.BigIntegerField(null=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="MemberPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("freshness_reminder_days", models.PositiveSmallIntegerField(default=3)),
                ("default_storage_mode", models.CharField(default="chilled", max_length=16)),
                ("favorite_recipe_ids", models.JSONField(default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.BigIntegerField()),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("role", models.CharField(max_length=16)),
                ("expires_at", models.BigIntegerField(db_index=True)),
                ("max_uses", models.PositiveSmallIntegerField(default=1)),
                ("used_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.BigIntegerField()),
                ("revoked_at", models.BigIntegerField(null=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("ingredient_id", models.CharField(max_length=80)),
                ("type", models.CharField(max_length=24)),
                ("quantity_delta", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit", models.CharField(max_length=16)),
                ("source_mutation_id", models.CharField(max_length=100)),
                ("occurred_at", models.BigIntegerField()),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("pantry_batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.pantrybatch")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=16)),
                ("status", models.CharField(default="active", max_length=16)),
                ("joined_at", models.BigIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.AddField(
            model_name="household",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="owned_households", to="api.user"
            ),
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                ("id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("device_id_hash", models.CharField(max_length=64)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.BigIntegerField()),
                ("expires_at", models.BigIntegerField(db_index=True)),
                ("last_seen_at", models.BigIntegerField()),
                ("revoked_at", models.BigIntegerField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="CookingRecord",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("recipe_id", models.CharField(max_length=80)),
                ("cooked_at", models.BigIntegerField()),
                ("servings", models.DecimalField(decimal_places=2, max_digits=8)),
                ("consumptions", models.JSONField(default=list)),
                ("mutation_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="AuthIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=32)),
                ("app_id", models.CharField(max_length=64)),
                ("provider_subject_hash", models.CharField(max_length=64)),
                ("created_at", models.BigIntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.BigIntegerField()),
                (
                    "household",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.household"),
                ),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=16)),
                ("requested_at", models.BigIntegerField()),
                ("execute_after", models.BigIntegerField(db_index=True)),
                ("cancelled_at", models.BigIntegerField(null=True)),
                ("completed_at", models.BigIntegerField(null=True)),
                ("blocked_reason", models.CharField(blank=True, max_length=200)),
                (
                    "restricted_session",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.devicesession"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="V1Migration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("import_batch_id", models.CharField(max_length=100)),
                ("checksum", models.CharField(max_length=64)),
                ("summary", models.JSONField()),
                ("source", models.TextField()),
                ("status", models.CharField(max_length=16)),
                ("created_at", models.BigIntegerField()),
                ("committed_at", models.BigIntegerField(null=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="SyncChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cursor", models.PositiveBigIntegerField()),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=8)),
                ("version", models.PositiveIntegerField()),
                ("payload", models.JSONField(null=True)),
                ("server_time", models.BigIntegerField()),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
            ],
            options={
                "indexes": [models.Index(fields=["household", "cursor"], name="api_synccha_househo_a099f8_idx")],
                "constraints": [models.UniqueConstraint(fields=("household", "cursor"), name="change_cursor_unique")],
            },
        ),
        migrations.CreateModel(
            name="RecipeProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipe_id", models.CharField(max_length=80)),
                ("status", models.CharField(default="unlockable", max_length=16)),
                ("unlocked_at", models.BigIntegerField(null=True)),
                ("cook_count", models.PositiveIntegerField(default=0)),
                ("last_cooked_at", models.BigIntegerField(null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("household", "user", "recipe_id"), name="progress_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedMutation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mutation_id", models.CharField(max_length=100)),
                ("result", models.JSONField()),
                ("processed_at", models.BigIntegerField()),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "mutation_id"), name="processed_mutation_unique")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="pantrybatch",
            index=models.Index(fields=["household", "ingredient_id", "status"], name="api_pantryb_househo_faba2d_idx"),
        ),
        migrations.AddConstraint(
            model_name="pantrybatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="batch_quantity_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberpreferences",
            constraint=models.UniqueConstraint(fields=("household", "user"), name="preferences_unique"),
        ),
        migrations.AddIndex(
            model_name="householdmember",
            index=models.Index(fields=["user", "status"], name="api_househo_user_id_3559be_idx"),
        ),
        migrations.AddIndex(
            model_name="householdmember",
            index=models.Index(fields=["household", "status"], name="api_househo_househo_2ca498_idx"),
        ),
        migrations.AddConstraint(
            model_name="householdmember",
            constraint=models.UniqueConstraint(fields=("household", "user"), name="membership_unique"),
        ),
        migrations.AddConstraint(
            model_name="authidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "app_id", "provider_subject_hash"), name="identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="v1migration",
            constraint=models.UniqueConstraint(fields=("user", "import_batch_id"), name="migration_unique"),
        ),
    ]
